# Project GATE

In [51]:
import sys
# !{sys.executable} -m pip install pyassimp
# !{sys.executable} -m conda install -c flyem-forge assimp
# !conda install --yes --prefix {sys.prefix} -c schrodinger pycollada

# path to module files
sys.path.insert(1, '../python_files/') # insert at 1, 0 is the script path (or '' in REPL)

import warnings
warnings.filterwarnings('ignore')

import numpy as np
from numpy import e
from clifford.g3c import *
from clifford.tools.g3c import *
# from pyganja_package import *
from pyassimp import *
# import igl
import meshplot as mp

## PyAssimp examples

In [52]:

scene = load('astroBoy_walk.dae')
# mesh = Collada('./models/cylinders_tris_only.dae', ignore=[DaeUnsupportedError, DaeBrokenRefError])
mesh = scene.meshes[0]
# print(len(mesh.vertices))
# print(len(mesh.normals))
# print(len(mesh.texturecoords))
# print(len(mesh.faces))
# print(len(mesh.bones))

# for b in mesh.bones:
#     print('-----------------------')
#     for w in b.weights:
#         print(w.weight)
        
# release(scene)

In [53]:
# print(mesh.vertices)


# scene = load('../models/astroBoy_walk.dae')
# scene = load('../models/cylinders_tris_only.dae')
# scene = load('../models/ManolisModelOnlyTris.fbx')
scene = load('astroBoy_walk.dae')
mesh = scene.meshes[0]
v = mesh.vertices
f = mesh.faces

# mesh = scene.meshes[0]
print(len(mesh.vertices))
print(len(mesh.normals))
print(len(mesh.texturecoords))
print(len(mesh.faces))
print(len(mesh.bones))

# for b in mesh.bones:
#     print('-----------------------')
#     for w in b.weights:
#         print(w.weight)
        
# release(scene)


p = mp.plot(v, f,v[:, 0],shading={"scale": 2.5},return_plot=True)

L = len(scene.meshes)
for i in range(1,L):
    mesh = scene.meshes[i]
    v = mesh.vertices
    f = mesh.faces
    p.add_mesh(v, f, v[:, 0],);

release(scene)


# p.save("./PDFs/astro_boy.html")

2006
2006
1
990
3


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 13.6…

### Experimenting with body bones

In [54]:
mesh = scene.meshes[0] 
v = mesh.vertices
f = mesh.faces
b = mesh.bones

for i in range(len(b)):
    print(i,b[i])

0 astroBoy_newSkeleton_spine02
1 astroBoy_newSkeleton_neck01
2 astroBoy_newSkeleton_head


In [55]:
scene = load('astroBoy_walk.dae')

def recur_node(node,level = 0):
#     print("  " + "\t" * level + "- " + str(node))
    print(str(level) + " " * level + "- " + str(node))
    for child in node.children:
        recur_node(child, level + 1)


        
print("NODES:")
recur_node(scene.rootnode)


# recur_node(scene.rootnode.children[3])
# recur_node(scene.rootnode.astroBoy_newSkeleton_root)

# print(scene.rootnode.children[3].children[0].children[0])


NODES:
0- VisualSceneNode
1 - astroBoy_newSkeleton_boy
1 - astroBoy_newSkeleton_pointLight1
1 - astroBoy_newSkeleton_ambientLight1
1 - astroBoy_newSkeleton_deformation_rig
2  - astroBoy_newSkeleton_root
3   - astroBoy_newSkeleton_spine01
4    - astroBoy_newSkeleton_spine02
5     - astroBoy_newSkeleton_neck01
6      - astroBoy_newSkeleton_head
7       - astroBoy_newSkeleton_headEnd
5     - astroBoy_newSkeleton_L_clavicle
6      - astroBoy_newSkeleton_L_shoulder
7       - astroBoy_newSkeleton_L_bicep
8        - astroBoy_newSkeleton_L_elbow
9         - astroBoy_newSkeleton_L_forearm
10          - astroBoy_newSkeleton_L_wrist
11           - astroBoy_newSkeleton_L_pinkyOrient
12            - astroBoy_newSkeleton_L_pinky_01
13             - astroBoy_newSkeleton_L_pinky_02
14              - astroBoy_newSkeleton_L_pinkyEnd
11           - astroBoy_newSkeleton_L_middleOrient
12            - astroBoy_newSkeleton_L_middle_01
13             - astroBoy_newSkeleton_L_middle_02
14              - astro

In [56]:
scene = load('astroBoy_walk.dae')
# scene = load('../models/ManosCubeScale123.fbx')
# scene = load('../models/ManosCube.dae')


mesh = scene.meshes[0] # body
v = mesh.vertices
f = mesh.faces
b = mesh.bones

boneID = 0
print(b[boneID]) # to onoma tou bone
print(len(b[boneID].weights)) # to plithos ton korifon pou epireazei to bone b[0]
print(b[boneID].weights[15].vertexid) # to 21o vertex pou epireazei to bone b[0]
print(b[boneID].weights[15].weight) # to antistoixo varos

print(len(v))

astroBoy_newSkeleton_spine02
16
1418
1.0
2006


In [57]:
M0 = b[0].offsetmatrix
print(b[0].offsetmatrix)
# print(b[1].offsetmatrix)
# print(b[2].offsetmatrix)

[[ 0.          0.19124199  0.981543   -1.47623003]
 [ 0.          0.981543   -0.19124199 -9.44237041]
 [-1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [58]:
M1 = b[0].offsetmatrix
# print(b[1].offsetmatrix)

In [59]:
# M2 = b[1].offsetmatrix
# print(b[2].offsetmatrix)

In [60]:
# M10 = np.dot(M1,M0)
# M210 = np.dot(M2,M10)
# print(M210)

In [66]:
def eulerAnglesToRotationMatrix(theta) :
     
    R_x = np.array([[1,         0,                  0                   ],
                    [0,         math.cos(theta[0]), -math.sin(theta[0]) ],
                    [0,         math.sin(theta[0]), math.cos(theta[0])  ]
                    ])
         
         
                     
    R_y = np.array([[math.cos(theta[1]),    0,      math.sin(theta[1])  ],
                    [0,                     1,      0                   ],
                    [-math.sin(theta[1]),   0,      math.cos(theta[1])  ]
                    ])
                 
    R_z = np.array([[math.cos(theta[2]),    -math.sin(theta[2]),    0],
                    [math.sin(theta[2]),    math.cos(theta[2]),     0],
                    [0,                     0,                      1]
                    ])
                     
                     
    R = np.dot(R_z, np.dot( R_y, R_x ))
 
    return R

M = eulerAnglesToRotationMatrix([1.5708,1.5708,0])
print("M=\n",M)

v = np.array([1,1,1])

D = np.diag([1,1/2,1/3])
print(D)

t = [2,2,2]

M2 = np.dot(D,M)
print(M2)

# 1st way
print(np.dot(M2,v)+t)

# 2nd way

M3 = np.zeros([4,4])
M3[0:3,0:3] = M2
M3[0:3,3] = np.transpose(t)
print(M3)
v3 = np.array([1,1,1,1])
print(np.dot(M3,v3))

M=
 [[-3.67320510e-06  1.00000000e+00 -3.67320510e-06]
 [ 0.00000000e+00 -3.67320510e-06 -1.00000000e+00]
 [-1.00000000e+00 -3.67320510e-06  1.34924357e-11]]
(3,)
[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[-3.67320510e-06  1.00000000e+00 -3.67320510e-06]
 [ 0.00000000e+00 -1.83660255e-06 -5.00000000e-01]
 [-3.33333333e-01 -1.22440170e-06  4.49747858e-12]]
[2.99999265 1.49999816 1.66666544]
[[-3.67320510e-06  1.00000000e+00 -3.67320510e-06  2.00000000e+00]
 [ 0.00000000e+00 -1.83660255e-06 -5.00000000e-01  2.00000000e+00]
 [-3.33333333e-01 -1.22440170e-06  4.49747858e-12  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
[2.99999265 1.49999816 1.66666544 0.        ]


In [62]:
R = eulerAnglesToRotationMatrix([1.5708,1.5708,0])
D = np.diag([1,1/2,1/3])

print(np.dot(D,R))
print(np.dot(R,D))

[[-3.67320510e-06  1.00000000e+00 -3.67320510e-06]
 [ 0.00000000e+00 -1.83660255e-06 -5.00000000e-01]
 [-3.33333333e-01 -1.22440170e-06  4.49747858e-12]]
[[-3.67320510e-06  5.00000000e-01 -1.22440170e-06]
 [ 0.00000000e+00 -1.83660255e-06 -3.33333333e-01]
 [-1.00000000e+00 -1.83660255e-06  4.49747858e-12]]


In [63]:
# Checks if a matrix is a valid rotation matrix.
def isRotationMatrix(R) :
    Rt = np.transpose(R)
    shouldBeIdentity = np.dot(Rt, R)
    I = np.identity(3, dtype = R.dtype)
    n = np.linalg.norm(I - shouldBeIdentity)
    return n < 1e-6
 
 
# Calculates rotation matrix to euler angles
# The result is the same as MATLAB except the order
# of the euler angles ( x and z are swapped ).
def rotationMatrixToEulerAngles(R) :
 
#     assert(isRotationMatrix(R))
     
    sy = math.sqrt(R[0,0] * R[0,0] +  R[1,0] * R[1,0])
     
    singular = sy < 1e-6
 
    if  not singular :
        x = math.atan2(R[2,1] , R[2,2])
        y = math.atan2(-R[2,0], sy)
        z = math.atan2(R[1,0], R[0,0])
    else :
        x = math.atan2(-R[1,2], R[1,1])
        y = math.atan2(-R[2,0], sy)
        z = 0
 
    return np.array([x, y, z])

B = b[0].offsetmatrix
M = B[0:3,0:3] 
Mt = np.transpose(M)


# rotationMatrixToEulerAngles(M)
print(np.dot(M,Mt))

[[1.00000017 0.         0.        ]
 [0.         1.00000017 0.        ]
 [0.         0.         1.        ]]


In [64]:
# see: http://ogldev.org/www/tutorial38/tutorial38.html

# print(scene.rootnode.children[0].children[0])
# print(scene.rootnode.children[0].children[0].children[0])
# print(scene.rootnode.children[0].children[0].children[0].parent)
# print(scene.rootnode.children[0].children[0].children[0].transformation)
# print(scene.rootnode.children[0].children[0].children[0].name)

# Model2

In [65]:
scene = load('astroBoy_walk.dae')
# v = np.reshape(v,((v.shape[0],1)))
# print(v)
# print(v.shape)
mesh = scene.meshes[0] # body
L = len(scene.meshes)
p = mp.plot(v, f,v[:, 0],shading={"scale": 2.5},return_plot=True)
for i in range(1,L):
    mesh = scene.meshes[i]
    v = mesh.vertices
    f = mesh.faces
    p.add_mesh(v, f, v[:, 0]);

release(scene)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
b = mesh.bones


boneID = 2
vertices_ids_affected_by_boneID = [b[boneID].weights[i].vertexid for i in range(len(b[boneID].weights))]


print("these are the points affected by ", b[boneID])
print("="*8)
print("ID  & Weight")
for i in range(len(b[boneID].weights)):
    print(b[boneID].weights[i].vertexid, b[boneID].weights[i].weight)
print("="*8)
# print(vertices_ids_affected_by_boneID)

these are the points affected by  joint3
ID  & Weight
0 0.49656298756599426
1 0.49656298756599426
2 0.49863201379776
3 0.49656298756599426
4 0.49863201379776
5 0.49863201379776
6 0.49656298756599426
7 0.49656298756599426
8 0.49656298756599426
9 0.49656298756599426
10 0.49656298756599426
11 0.49656298756599426
12 0.49863201379776
13 0.49863201379776
14 0.49656298756599426
15 0.49863201379776
16 0.49656298756599426
17 0.49656298756599426
18 0.49863201379776
19 0.49863201379776
20 0.49863201379776
21 0.49863201379776
22 0.49863201379776
23 0.49863201379776
24 0.49656298756599426
25 0.49863201379776
26 0.49656298756599426
27 0.49863201379776
28 0.49863201379776
29 0.49656298756599426
30 0.49656298756599426
31 0.49863201379776
32 0.49863201379776
33 0.49863201379776
34 0.49656298756599426
35 0.49656298756599426
36 0.4969330132007599
37 0.006134999915957451
38 0.4969330132007599
39 0.4969330132007599
40 0.006134999915957451
41 0.006134999915957451
42 0.4969330132007599
43 0.4969330132007599


In [ ]:
M0 = b[0].offsetmatrix
M1 = b[1].offsetmatrix
M2 = b[2].offsetmatrix

In [ ]:
def vertex_view_from_M(v,M):
    return np.dot(M,np.append(v,[1.0]))[0:3]

print(v[0])
print(vertex_view_from_M(v[0],M0))

1


ValueError: shapes (4,4) and (2,) not aligned: 4 (dim 1) != 2 (dim 0)

In [ ]:
R = eulerAnglesToRotationMatrix([1.5708,1.5708,0])
N = np.zeros([4,4])
N[0:3,0:3] = R
N[3,3] = 1

v_origin = v[0]
v_after_M = vertex_view_from_M(v_origin,np.dot(N,M0))
print(v_origin)
print(v_after_M)


ValueError: shapes (4,4) and (2,) not aligned: 4 (dim 1) != 2 (dim 0)

In [ ]:
print("="*8)
print(scene.rootnode.children[0].children[0])
N0 = scene.rootnode.children[0].children[0].transformation
print("N0=",N0)
print("="*8)
print("="*8)
print(scene.rootnode.children[0].children[0])
N0 = scene.rootnode.children[0].children[0].transformation
print("N0=",N0)
print("="*8)
print("M0=",M0)
print("="*8)
print("="*8)
print(scene.rootnode.children[0].children[0].children[0])
N1 = scene.rootnode.children[0].children[0].children[0].transformation
print("N1=",N1)
print("="*8)
print("M1=",M1)
print("="*8)
print("="*8)
print(scene.rootnode.children[0].children[0].children[0].children[0])
N2 = scene.rootnode.children[0].children[0].children[0].children[0].transformation
print("N2=",N2)
print("="*8)
print("M2=",M2)
print("="*8)

N12 = np.dot(N1,N2)
N012 = np.dot(N0,N12)
print("N0*N1*N2=",N012)
print("N0*N1*N2*M2=",np.dot(N012,M2))

print("="*8)
N01 = np.dot(N0,N1)
print("N0*N1=",N01)
print("N0*N1*M1=",np.dot(N01,M1))
# print(scene.rootnode.children[0].children[0].children[0].parent)
# print(scene.rootnode.children[0].children[0].children[0].transformation)
# print(scene.rootnode.children[0].children[0].children[0].name)

joint1
N0= [[ 0.38613901  0.         -0.92244101  0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.92244101  0.          0.38613901  0.        ]
 [ 0.          0.          0.          1.        ]]
joint1
N0= [[ 0.38613901  0.         -0.92244101  0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.92244101  0.          0.38613901  0.        ]
 [ 0.          0.          0.          1.        ]]
M0= [[ 0.38613901  0.          0.92244101  0.        ]
 [ 0.          1.         -0.          0.        ]
 [-0.92244101  0.          0.38613901  0.        ]
 [ 0.          0.          0.          1.        ]]
joint2
N1= [[ 0.999888  0.        0.014984  0.      ]
 [ 0.        1.        0.        3.      ]
 [-0.014984  0.        0.999888  0.      ]
 [ 0.        0.        0.        1.      ]]
M1= [[ 0.39991799  0.          0.91655099  0.        ]
 [ 0.          1.         -0.         -3.        ]
 [-0.91655099  0.          0.39991799  0.        ]
 [ 0.          0. 

In [ ]:
N0 = scene.rootnode.children[0].children[0].transformation
global_inverse_transform=numpy.linalg.inv(N0) # N0^{-1} = M0 = global_inverse_transform
# print("N0=",N0) 
# or 
#print("M0=",M0)

parent = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
Transform_matrix =  np.array([[1,0,0,5],[0,1,0,3],[0,0,1,2],[0,0,0,1]])
global_transformation_1 = np.dot(parent,Transform_matrix)
Final_transform_1 = np.dot(global_inverse_transform,global_transformation_1)
Final_transform_1 = np.dot(Final_transform_1,M1)
print(Final_transform_1)

Transform_matrix =  np.array([[1,0,0,15],[0,1,0,13],[0,0,1,12],[0,0,0,1]])
global_transformation_2 = np.dot(global_transformation_1,Transform_matrix)
Final_transform_2 = np.dot(global_inverse_transform,global_transformation_2)
Final_transform_2 = np.dot(Final_transform_2,M2)
print(Final_transform_2)




[[-0.69103977  0.          0.72281631  3.77557424]
 [ 0.          1.          0.          0.        ]
 [-0.72281631  0.         -0.69103977 -3.83992417]
 [ 0.          0.          0.          1.        ]]
[[  0.38613872   0.           0.92244032  20.63693891]
 [  0.           1.           0.          11.        ]
 [ -0.92244032   0.           0.38613872 -13.04286438]
 [  0.           0.           0.           1.        ]]


# Model 4

In [ ]:
scene = load('astroBoy_walk.dae')
mesh = scene.meshes[0] 
v = mesh.vertices
f = mesh.faces
L = len(scene.meshes)
p = mp.plot(v, f,v[:, 0],shading={"scale": 2.5},return_plot=True)
for i in range(1,L):
    mesh = scene.meshes[i]
    v = mesh.vertices
    f = mesh.faces
    p.add_mesh(v, f, v[:, 0]);

release(scene)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 2.90…

In [ ]:
M0 = b[0].offsetmatrix
M1 = b[1].offsetmatrix
M2 = b[2].offsetmatrix

print("="*8)
print(scene.rootnode.children[0])
N0 = scene.rootnode.children[0].transformation
print("N0=",N0)
print("="*8)
print("M0=",M0)
print("="*8)
print("="*8)
print(scene.rootnode.children[0].children[0])
N1 = scene.rootnode.children[0].children[0].transformation
print("N1=",N1)
print("="*8)
print("M1=",M1)
print("="*8)
print("="*8)
print(scene.rootnode.children[0].children[0].children[0])
N2 = scene.rootnode.children[0].children[0].children[0].transformation
print("N2=",N2)
print("="*8)
print("M2=",M2)
print("="*8)

joint1
N0= [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M0= [[ 0.38613901  0.          0.92244101  0.        ]
 [ 0.          1.         -0.          0.        ]
 [-0.92244101  0.          0.38613901  0.        ]
 [ 0.          0.          0.          1.        ]]
joint2
N1= [[1. 0. 0. 0.]
 [0. 1. 0. 3.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M1= [[ 0.39991799  0.          0.91655099  0.        ]
 [ 0.          1.         -0.         -3.        ]
 [-0.91655099  0.          0.39991799  0.        ]
 [ 0.          0.          0.          1.        ]]
joint3
N2= [[1. 0. 0. 0.]
 [0. 1. 0. 2.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M2= [[ 1.  0.  0.  0.]
 [ 0.  1.  0. -5.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [ ]:
from numpy import dot
v0 = np.array([0.4, 5.8, 0.4, 1.0])
dot(N0,dot(M0,v0))

array([ 0.523432 ,  5.8      , -0.2145208,  1.       ])

In [ ]:
N0 = scene.rootnode.children[0].transformation
global_inverse_transform=numpy.linalg.inv(N0) # N0^{-1} = M0 = global_inverse_transform
# print("N0=",N0) 
# or 
#print("M0=",M0)



parent = np.identity(4)
Transform_matrix = np.identity(4)
global_transformation_0 = np.dot(parent,Transform_matrix)
Final_transform_0 = np.dot(global_inverse_transform,global_transformation_0)
Final_transform_0 = np.dot(Final_transform_0,M0)
print(Final_transform_0)



parent = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
Transform_matrix =  np.array([[1,0,0,1],[0,1,0,3],[0,0,1,2],[0,0,0,1]])
global_transformation_1 = np.dot(global_transformation_0,Transform_matrix)
Final_transform_1 = np.dot(global_inverse_transform,global_transformation_1)
Final_transform_1 = np.dot(Final_transform_1,M1)
print(Final_transform_1)


R = eulerAnglesToRotationMatrix([0.7,0.7,0.7])
myT = np.zeros([4,4])
myT[0:3,0:3] = R
myT[3,3]=1
# print(myT)


# Transform_matrix =  np.array([[1,0,0,5],[0,1,0,3],[0,0,1,3],[0,0,0,1]])
Transform_matrix =  myT
global_transformation_2 = np.dot(global_transformation_1,Transform_matrix)
Final_transform_2 = np.dot(global_inverse_transform,global_transformation_2)
Final_transform_2 = np.dot(Final_transform_2,M2)
print(Final_transform_2)



[[ 0.38613901  0.          0.92244101  0.        ]
 [ 0.          1.          0.          0.        ]
 [-0.92244101  0.          0.38613901  0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 0.39991799  0.          0.91655099  1.        ]
 [ 0.          1.          0.          0.        ]
 [-0.91655099  0.          0.39991799  2.        ]
 [ 0.          0.          0.          1.        ]]
[[ 0.58498357 -0.17530279  0.79187319  1.87651396]
 [ 0.49272486  0.8523445  -0.17530279 -1.26172248]
 [-0.64421769  0.49272486  0.58498357 -0.46362432]
 [ 0.          0.          0.          1.        ]]


In [ ]:
scene = load('astroBoy_walk.dae')
mesh = scene.meshes[0] # body
v = mesh.vertices
f = mesh.faces
b = mesh.bones
L = len(scene.meshes)
# p = mp.plot(v, f,v[:, 0],shading={"scale": 2.5},return_plot=True)
# for i in range(1,L):
#     mesh = scene.meshes[i]
#     v = mesh.vertices
#     f = mesh.faces
#     p.add_mesh(v, f, v[:, 0]);

# release(scene)


def vertex_apply_M(v,M):
    return np.dot(M,np.append(v,[1.0]))[0:3]

b = mesh.bones

# print("these are the points affected by ", b[boneID])
# print("="*8)
# print("ID  & Weight")

# boneID = 1
# for i in range(len(b[boneID].weights)):
#     vID = b[boneID].weights[i].vertexid
# #     print(b[boneID].weights[i].vertexid, b[boneID].weights[i].weight)
#     v[vID] = v[vID]+vertex_apply_M(v[vID],Final_transform_1)*b[boneID].weights[i].vertexid
# print("="*8)


boneID = 2
for i in range(len(b[boneID].weights)):
    vID = b[boneID].weights[i].vertexid
#     print(b[boneID].weights[i].vertexid, b[boneID].weights[i].weight)
    v[vID] = vertex_apply_M(v[vID],Final_transform_2)
print("="*8)

p = mp.plot(v, f,v[:, 0],shading={"scale": 2.5},return_plot=True)
# for i in range(1,L):
#     mesh = scene.meshes[i]
#     v = mesh.vertices
#     f = mesh.faces
#     p.add_mesh(v, f, v[:, 0]);

release(scene)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.2753713…

In [ ]:
b = mesh.bones


boneID = 1
vertices_ids_affected_by_boneID = [b[boneID].weights[i].vertexid for i in range(len(b[boneID].weights))]


print("these are the points affected by ", b[boneID])
print("="*8)
print("ID  & Weight")
for i in range(len(b[boneID].weights)):
    print(b[boneID].weights[i].vertexid, b[boneID].weights[i].weight)
print("="*8)
# print(vertices_ids_affected_by_boneID)

these are the points affected by  joint2
ID  & Weight
36 0.9878050088882446
37 0.5
38 0.9878050088882446
39 0.9878050088882446
40 0.5
41 0.5
42 0.9878050088882446
43 0.9878050088882446
44 0.9878050088882446
45 0.9878050088882446
46 0.9878050088882446
47 0.9878050088882446
48 0.5
49 0.9878050088882446
50 0.5
51 0.5
52 0.9878050088882446
53 0.9878050088882446
54 0.5
55 0.5
56 0.5
57 0.5
58 0.5
59 0.5
60 0.5
61 0.9878050088882446
62 0.5
63 0.9878050088882446
64 0.5
65 0.9878050088882446
66 0.9878050088882446
67 0.5
68 0.5
69 0.5
70 0.9878050088882446
71 0.9878050088882446
72 0.5
73 0.009901000186800957
74 0.009901000186800957
75 0.009901000186800957
76 0.5
77 0.5
78 0.5
79 0.009901000186800957
80 0.009901000186800957
81 0.009901000186800957
82 0.5
83 0.5
84 0.5
85 0.009901000186800957
86 0.009901000186800957
87 0.009901000186800957
88 0.5
89 0.5
90 0.5
91 0.009901000186800957
92 0.5
93 0.5
94 0.009901000186800957
95 0.009901000186800957
96 0.009901000186800957
97 0.5
98 0.0099010001868009

# Model 2

In [ ]:
scene = load('astroBoy_walk.dae')
mesh = scene.meshes[0] 
v = mesh.vertices
f = mesh.faces
L = len(scene.meshes)
p = mp.plot(v, f,v[:, 0],shading={"scale": 2.5},return_plot=True)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 2.90…

In [ ]:
b = mesh.bones
B0 = b[0].offsetmatrix
B1 = b[1].offsetmatrix
B2 = b[2].offsetmatrix



# print("="*8)
# print(scene.rootnode.children[0])
# N0 = scene.rootnode.children[0].transformation
# print("N0=",N0)
# print("="*8)
print("="*8)
print(scene.rootnode.children[0].children[0])
T0 = scene.rootnode.children[0].children[0].transformation
print("T0=",T0)
print("="*8)
print(scene.rootnode.children[0].children[0].children[0])
T1 = scene.rootnode.children[0].children[0].children[0].transformation
print("T1=",T1)
print("="*8)
print(scene.rootnode.children[0].children[0].children[0].children[0])
T2 = scene.rootnode.children[0].children[0].children[0].children[0].transformation
print("T2=",T2)
print("="*8)


joint1
T0= [[ 0.38613901  0.         -0.92244101  0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.92244101  0.          0.38613901  0.        ]
 [ 0.          0.          0.          1.        ]]
joint2
T1= [[ 0.999888  0.        0.014984  0.      ]
 [ 0.        1.        0.        3.      ]
 [-0.014984  0.        0.999888  0.      ]
 [ 0.        0.        0.        1.      ]]
joint3
T2= [[ 0.39991799  0.          0.91655099  0.        ]
 [ 0.          1.          0.          2.        ]
 [-0.91655099  0.          0.39991799  0.        ]
 [ 0.          0.          0.          1.        ]]


In [ ]:
b = mesh.bones


class vertex_weight:
  def __init__(self):
    self.id = np.full([len(v),4],-1)
    self.weight = np.zeros([len(v),4])

  def add(self,v,b,w):
    position = 0
    while self.weight[v][position] and position < 3: 
        position +=1
#     print(position)
    if position < 4:
        self.weight[v][position]=w
        self.id[v][position]=b


vw = vertex_weight()
for boneID in range(len(b)):
    for i in range(len(b[boneID].weights)):
        vw.add(b[boneID].weights[i].vertexid, boneID ,b[boneID].weights[i].weight)

# print(vw.id)

def B(x):
    if x == 0:
        return B0
    elif x == 1:
        return B1
    elif x == 2:
        return B2

def T(x):
    if x == 0:
        return T0
#         return np.identity(4)
    elif x == 1:
        return T1
    elif x == 2:
        return T2

# print(np.dot(T))
  
def vertex_apply_M(v,M):
    return np.dot(M,np.append(v,[1.0]))[0:3]
    
    
newv = np.zeros([(len(v)),3])

for i in range(len(v)):
    for j in range(3):
        if vw.id[i][j] >=0:
            mat = np.dot(T(j),B(j))
#             print(i,j)
            newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))


# print(newv)

p = mp.plot(newv, f,v[:, 0],shading={"scale": 2.5},return_plot=True)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 2.15…

In [ ]:
print(T2)

[[ 0.39991799  0.          0.91655099  0.        ]
 [ 0.          1.          0.          2.        ]
 [-0.91655099  0.          0.39991799  0.        ]
 [ 0.          0.          0.          1.        ]]


In [ ]:

class vertex_weight:
  def __init__(self):
    self.id = np.zeros([len(v),4])
    self.weight = np.zeros([len(v),4])

  def add(self,v,b,w):
    position = 0
    while self.weight[v][position] and position < 3: 
        position +=1
#     print(position)
    if position < 4:
        self.weight[v][position]=w
        self.id[v][position]=b

test = vertex_weight()
test.add(1,2,1)
test.add(1,3,1)
test.add(1,4,1)
test.add(1,5,0.7)
test.add(1,6,0.7)
test.add(1,7,0.7)
print(test.id[0:3,:])
print(test.weight[0:3,:])



[[0. 0. 0. 0.]
 [2. 3. 4. 7.]
 [0. 0. 0. 0.]]
[[0.  0.  0.  0. ]
 [1.  1.  1.  0.7]
 [0.  0.  0.  0. ]]


In [ ]:
v[0]

array([0.4, 5.8, 0.4], dtype=float32)

In [ ]:
from numpy import dot
v0 = np.array([0.4, 5.8, 0.4, 1.0])
dot(N0,dot(M0,v0))

array([ 0.523432 ,  5.8      , -0.2145208,  1.       ])

# Looking Better

In [ ]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
from numpy import e
from clifford.g3c import *
from clifford.tools.g3c import *
# from pyganja_package import *
from pyassimp import *
import igl
import meshplot as mp

ModuleNotFoundError: No module named 'igl'

In [ ]:
# =================================================
# Creating a class that contains the vertices and 
# and the respective weights that are affected by the
# bones. 
# =================================================
class vertex_weight:
  def __init__(self):
    self.id = np.full([len(v),4],-1)
    self.weight = np.zeros([len(v),4])

  def add(self,v,b,w):
    position = 0
    while self.weight[v][position] and position < 3: 
        position +=1
#     print(position)
    if position < 4:
        self.weight[v][position]=w
        self.id[v][position]=b

def B(x):
    return b[x].offsetmatrix

def read_tree(node):
    if node.name in bone_names:
        index = bone_names.index(node.name)
        t[index] = node.transformation
    for child in node.children:
        read_tree(child)
        

def eulerAnglesToRotationMatrix(theta) :  
    R_x = np.array([[1,         0,                  0                   ],
                    [0,         math.cos(theta[0]), -math.sin(theta[0]) ],
                    [0,         math.sin(theta[0]), math.cos(theta[0])  ]
                    ])                    
    R_y = np.array([[math.cos(theta[1]),    0,      math.sin(theta[1])  ],
                    [0,                     1,      0                   ],
                    [-math.sin(theta[1]),   0,      math.cos(theta[1])  ]
                    ])             
    R_z = np.array([[math.cos(theta[2]),    -math.sin(theta[2]),    0],
                    [math.sin(theta[2]),    math.cos(theta[2]),     0],
                    [0,                     0,                      1]
                    ])                  
    R = np.dot(R_z, np.dot( R_y, R_x ))
    return R

def T(x,transform = True):
    if x == 0:
        return np.dot(t[0],M[0]) if transform else t[0]
    else :
        return np.dot(np.dot(T(x-1),t[x]),M[x]) if transform else np.dot(T(x-1,False),t[x])

def vertex_apply_M(v,M):
    return np.dot(M,np.append(v,[1.0]))[0:3]

def bone_position(i):
    return T(i)[0:3,3]

In [ ]:
# scene = load('../models/ManosModel2.dae')
scene = load('astroBoy_walk.dae')
mesh = scene.meshes[0] 
v = mesh.vertices
f = mesh.faces
b = mesh.bones



vw = vertex_weight()
for boneID in range(len(b)):
    for i in range(len(b[boneID].weights)):
        vw.add(b[boneID].weights[i].vertexid, boneID ,b[boneID].weights[i].weight)


# =================================================
# EVALUATING TRANSFORMATION MATRICES IN ELEGANT WAY
# =================================================
# original way was :
# t0 = scene.rootnode.children[0].children[0].transformation
# t1 = scene.rootnode.children[0].children[0].children[0].transformation
# t2 = scene.rootnode.children[0].children[0].children[0].children[0].transformation

bone_names = [str(b[i]) for i in range(len(b))]
t = np.zeros([len(b),4,4])
read_tree(scene.rootnode)

# for i in range(len(b)):
#     t[i,0:3,0:3] = np.identity(3)
# print(t)


# =================================================
# APPLYING EXTRA TRANSFORMATIONS IN JOINTS
# =================================================
M = np.zeros([len(b),4,4])
for i in range(len(b)):
    M[i] = np.identity(4)

    
# M[0][0:3,0:3] = eulerAnglesToRotationMatrix([0.2,0,0])
    
M[1][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.4])

M[2][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.4])

# =================================================
    
newv = np.zeros([(len(v)),3])
for i in range(len(v)):
    for j in range(3):
        if vw.id[i][j] >=0:
            mat = np.dot(T(j),B(j))
            newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))


p = mp.plot(newv, f,v[:, 0],shading={"scale": 2.5,"side": "BackSide","wireframe":True},return_plot=True)
# p = mp.plot(newv,f,shading={"scale": 2.5,"point_size": 1,"wireframe":True},return_plot=True)

if len(b)>0:
    for i in range(len(b)-1):
        p.add_lines(bone_position(i),bone_position(i+1), shading={"line_color": "yellow"});

bone_pos = np.array([bone_position(i) for i in range(len(b))])

p.add_points(bone_pos,shading={"point_color": "yellow","point_size": 2})
# print(type(bone_position(0)))

p.add_lines(v[f[:,0]], v[f[:,1]], shading={"line_color": "red"});
p.add_lines(v[f[:,2]], v[f[:,1]], shading={"line_color": "red"});
p.add_lines(v[f[:,2]], v[f[:,0]], shading={"line_color": "red"});

# p.save("skinning.html")
#     print(bone_position(2))
# p = mp.plot(newv, f,v[:, 0],shading={"flat":True,"scale": 2.5,"wireframe":True, "wire_width": 0.03, "wire_color": "black"},return_plot=True)

# p = mp.plot(newv,return_plot=True)
# p.add_lines(newv[f[:,0]], newv[f[:,1]], shading={"line_color": "red"});
# p.add_lines(newv[f[:,2]], newv[f[:,1]], shading={"line_color": "red"});
# p.add_lines(newv[f[:,2]], newv[f[:,0]], shading={"line_color": "red"});

# p.save('2o.html')

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0080254…

Plot saved to file 2o.html.


# Model: cylinders_tris_only

In [ ]:
# IMPORTANT NOTE: 
# 1. There are 2 meshes
# 2. To properly represent the 2nd mesh, we have to go to model space.

# scene = load('../models/ManosModel2.dae')
scene = load('astroBoy_walk.dae')
mesh = scene.meshes[0] 
v = mesh.vertices
f = mesh.faces
b = mesh.bones



vw = vertex_weight()
for boneID in range(len(b)):
    for i in range(len(b[boneID].weights)):
        vw.add(b[boneID].weights[i].vertexid, boneID ,b[boneID].weights[i].weight)


# =================================================
# EVALUATING TRANSFORMATION MATRICES IN ELEGANT WAY
# =================================================
# original way was :
# t0 = scene.rootnode.children[0].children[0].transformation
# t1 = scene.rootnode.children[0].children[0].children[0].transformation
# t2 = scene.rootnode.children[0].children[0].children[0].children[0].transformation

bone_names = [str(b[i]) for i in range(len(b))]
t = np.zeros([len(b),4,4])
read_tree(scene.rootnode)

# for i in range(len(b)):
#     t[i,0:3,0:3] = np.identity(3)
# print(t)


# =================================================
# APPLYING EXTRA TRANSFORMATIONS IN JOINTS
# =================================================
M = np.zeros([len(b),4,4])
for i in range(len(b)):
    M[i] = np.identity(4)

    
# M[0][0:3,0:3] = eulerAnglesToRotationMatrix([0.2,0,0])
    
M[1][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.4])

M[2][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.4])

# =================================================
    
newv = np.zeros([(len(v)),3])
for i in range(len(v)):
    for j in range(3):
        if vw.id[i][j] >=0:
            mat = np.dot(T(j),B(j))
            newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))


p = mp.plot(newv, f,v[:, 0],shading={"scale": 2.5,"side": "BackSide","wireframe":True},return_plot=True)
# p = mp.plot(newv,f,shading={"scale": 2.5,"point_size": 1,"wireframe":True},return_plot=True)

if len(b)>0:
    for i in range(len(b)-1):
        p.add_lines(bone_position(i),bone_position(i+1), shading={"line_color": "yellow"});

bones = np.array([bone_position(0),bone_position(1),bone_position(2)])

p.add_points(bones,shading={"point_color": "yellow","point_size": 2})
# print(type(bone_position(0)))

p.add_lines(v[f[:,0]], v[f[:,1]], shading={"line_color": "red"});
p.add_lines(v[f[:,2]], v[f[:,1]], shading={"line_color": "red"});
p.add_lines(v[f[:,2]], v[f[:,0]], shading={"line_color": "red"});


####################################
####################################
mesh = scene.meshes[1] 
v = mesh.vertices
f = mesh.faces
b = mesh.bones



vw = vertex_weight()
for boneID in range(len(b)):
    for i in range(len(b[boneID].weights)):
        vw.add(b[boneID].weights[i].vertexid, boneID ,b[boneID].weights[i].weight)


# =================================================
# EVALUATING TRANSFORMATION MATRICES IN ELEGANT WAY
# =================================================
# original way was :
# t0 = scene.rootnode.children[0].children[0].transformation
# t1 = scene.rootnode.children[0].children[0].children[0].transformation
# t2 = scene.rootnode.children[0].children[0].children[0].children[0].transformation

bone_names = [str(b[i]) for i in range(len(b))]
t = np.zeros([len(b),4,4])
read_tree(scene.rootnode)

# for i in range(len(b)):
#     t[i,0:3,0:3] = np.identity(3)
# print(t)


# =================================================
# APPLYING EXTRA TRANSFORMATIONS IN JOINTS
# =================================================
M = np.zeros([len(b),4,4])
for i in range(len(b)):
    M[i] = np.identity(4)

    
# M[0][0:3,0:3] = eulerAnglesToRotationMatrix([0.2,0,0])
    
M[1][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.4])

M[2][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.4])

# =================================================
    
newv = np.zeros([(len(v)),3])
for i in range(len(v)):
    for j in range(3):
        if vw.id[i][j] >=0:
            mat = np.dot(T(j),B(j))
            newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))


p.add_mesh(newv, f,v[:, 0],shading={"scale": 2.5,"side": "BackSide","wireframe":True})
# p = mp.plot(newv,f,shading={"scale": 2.5,"point_size": 1,"wireframe":True},return_plot=True)

if len(b)>0:
    for i in range(len(b)-1):
        p.add_lines(bone_position(i),bone_position(i+1), shading={"line_color": "yellow"});

bones = np.array([bone_position(0),bone_position(1),bone_position(2)])

p.add_points(bones,shading={"point_color": "yellow","point_size": 2})
# print(type(bone_position(0)))



newv = np.zeros([(len(v)),3])
for i in range(len(v)):
    for j in range(3):
        if vw.id[i][j] >=0:
            mat = np.dot(T(j,False),B(j))
            newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))


p.add_lines(newv[f[:,0]], newv[f[:,1]], shading={"line_color": "red"});
p.add_lines(newv[f[:,2]], newv[f[:,1]], shading={"line_color": "red"});
p.add_lines(newv[f[:,2]], newv[f[:,0]], shading={"line_color": "red"});



# p.save("cylinders.html")

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0105997…

## Fixing t_i

In [ ]:
scene = load('astroBoy_walk.dae')
mesh = scene.meshes[0] 
b = mesh.bones
v = mesh.vertices

bone_names = [str(b[i]) for i in range(len(b))]
print(bone_names)

t = np.zeros([len(b),4,4])

def read_tree(node):
    if node.name in bone_names:
        index = bone_names.index(node.name)
        t[index] = node.transformation
    for child in node.children:
        read_tree(child)

read_tree(scene.rootnode)
print(t)

['joint1', 'joint2', 'joint3']
[[[ 0.38613901  0.         -0.92244101  0.        ]
  [ 0.          1.          0.          0.        ]
  [ 0.92244101  0.          0.38613901  0.        ]
  [ 0.          0.          0.          1.        ]]

 [[ 0.999888    0.          0.014984    0.        ]
  [ 0.          1.          0.          3.        ]
  [-0.014984    0.          0.999888    0.        ]
  [ 0.          0.          0.          1.        ]]

 [[ 0.39991799  0.          0.91655099  0.        ]
  [ 0.          1.          0.          2.        ]
  [-0.91655099  0.          0.39991799  0.        ]
  [ 0.          0.          0.          1.        ]]]


# TEST AREA BELOW from skinning notebook

In [ ]:
# =================================================
# Creating a class that contains the vertices and 
# and the respective weights that are affected by the
# bones. 
# =================================================



class vertex_weight:
  def __init__(self):
    self.id = np.full([len(v),4],-1)
    self.weight = np.zeros([len(v),4])

  def add(self,v,b,w):
    position = 0
    for i in range(4):
        if self.weight[v][position]>0 :
            position +=1
    if position <= 4:
        self.weight[v][position]=w
        self.id[v][position]=b

def B(x):
    return b[x].offsetmatrix
#     if x == 0:
#         return b[x].offsetmatrix
#     else :
#         return np.dot(B(x-1),b[x].offsetmatrix)
  


def read_tree(node):
    if node.name in bone_names:
        index = bone_names.index(node.name)
        t[index] = node.transformation
    for child in node.children:
        read_tree(child)
        

def eulerAnglesToRotationMatrix(theta) :  
    R_x = np.array([[1,         0,                  0                   ],
                    [0,         math.cos(theta[0]), -math.sin(theta[0]) ],
                    [0,         math.sin(theta[0]), math.cos(theta[0])  ]
                    ])                    
    R_y = np.array([[math.cos(theta[1]),    0,      math.sin(theta[1])  ],
                    [0,                     1,      0                   ],
                    [-math.sin(theta[1]),   0,      math.cos(theta[1])  ]
                    ])             
    R_z = np.array([[math.cos(theta[2]),    -math.sin(theta[2]),    0],
                    [math.sin(theta[2]),    math.cos(theta[2]),     0],
                    [0,                     0,                      1]
                    ])                  
    R = np.dot(R_z, np.dot( R_y, R_x ))
    return R

def T(x,transform = True):
    if x == 0:
        return np.dot(t[0],M[0]) if transform else t[0]
    else :
        return np.dot(np.dot(T(x-1),t[x]),M[x]) if transform else np.dot(T(x-1,False),t[x])

def vertex_apply_M(v,M):
    return np.dot(M,np.append(v,[1.0]))[0:3]

def bone_position(i,transform = True):
    return T(i,transform)[0:3,3]

def draw_original_wireframe():
    p.add_lines(v[f[:,0]], v[f[:,1]], shading={"line_color": "magenta"});
    p.add_lines(v[f[:,2]], v[f[:,1]], shading={"line_color": "magenta"});
    p.add_lines(v[f[:,2]], v[f[:,0]], shading={"line_color": "magenta"});

    
def draw_bones():  
#     transform = True
    transform = False
    bone_pos = np.array([bone_position(i,transform) for i in range(len(b))])
    p.add_points(bone_pos,shading={"point_color": "yellow","point_size": 0.6})
    if len(b)>0:
        for i in range(len(b)-1):
            p.add_lines(bone_position(i,transform),bone_position(i+1,transform), shading={"line_color": "yellow"});

def draw_vertices_affected_by_boneID(boneID):
    vertices_ids_affected_by_boneID = [b[boneID].weights[i].vertexid for i in range(len(b[boneID].weights))]
    IDs = vertices_ids_affected_by_boneID
    print("red points are the ones affected by :", b[boneID])
    p.add_points(v[IDs], shading={"point_size": 0.7,"point_color": "red"}); 

# Euclidean Method -> Models Working: ManosModeld, ManosModel2

TODO
* Check if B(i) has to be implemented recursively, in order to correctly load AstroBoy


In [ ]:
# Problematic Models
# scene = load('../models/ManosModelc.dae','dae')

# proc = (pyassimp.postprocess.aiProcess_Triangulate  | 
#         pyassimp.postprocess.aiProcess_GenSmoothNormals | 
#         pyassimp.postprocess.aiProcess_FlipUVs | 
#         pyassimp.postprocess.aiProcess_SortByPType | 
#         pyassimp.postprocess.aiProcess_LimitBoneWeights | 
#         pyassimp.postprocess.aiProcess_SplitByBoneCount | 
#         pyassimp.postprocess.aiProcess_JoinIdenticalVertices | 
#         pyassimp.postprocess.aiProcess_FindInvalidData | 
#         pyassimp.postprocess.aiProcess_FindDegenerates | 
#         pyassimp.postprocess.aiProcess_RemoveRedundantMaterials | 
#         pyassimp.postprocess.aiProcess_ImproveCacheLocality | 
#         pyassimp.postprocess.aiProcess_SplitLargeMeshes |  
#         pyassimp.postprocess.aiProcess_ValidateDataStructure)
# scene = load('../models/ManosModelc.dae','dae',processing=proc)


# scene = load('../models/ManosModel2.dae')
# scene = load('../models/ManosModeld.dae','dae')
scene = load('astroBoy_walk.dae')

mesh = scene.meshes[0] 
v = mesh.vertices
f = mesh.faces
b = mesh.bones

vw = vertex_weight()
for boneID in range(len(b)):
    for i in range(len(b[boneID].weights)):
        vw.add(b[boneID].weights[i].vertexid, boneID ,b[boneID].weights[i].weight)
        
# =================================================
# EVALUATING TRANSFORMATION MATRICES IN ELEGANT WAY
# =================================================
# original way was :
# t0 = scene.rootnode.children[0].children[0].transformation
# t1 = scene.rootnode.children[0].children[0].children[0].transformation
# t2 = scene.rootnode.children[0].children[0].children[0].children[0].transformation

bone_names = [str(b[i]) for i in range(len(b))]
t = np.zeros([len(b),4,4])
read_tree(scene.rootnode)


# =================================================
# APPLYING EXTRA TRANSFORMATIONS IN JOINTS
# =================================================
M = np.zeros([len(b),4,4])
for i in range(len(b)):
    M[i] = np.identity(4)

# M[0][0:3,0:3] = eulerAnglesToRotationMatrix([0.5,0,0]) 
# M[0][0:3,3] = [1,1,0]
# M[0] = np.dot(M[0],np.diag([1,1,1,1]))

M[1][0:3,0:3] = eulerAnglesToRotationMatrix([0.7,0.3,0.4])
M[1][0:3,3] = [0,0,0]
M[1] = np.dot(np.diag([1,1.3,1,1]),M[1])

# M[2][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.7])
# M[2][0:3,3] = [0,0,0]
# M[2] = np.dot(M[2],np.diag([1,1/2,1,1]))


# =================================================
        
newv = np.zeros([(len(v)),3])

TTrue = [T(i,True) for i in range(len(b))]
TFalse = [T(i,False) for i in range(len(b))]
BB = [B(i) for i in range(len(b))]

import time

start = time.time()
for i in range(len(v)):
    for j in range(4):
        if vw.id[i][j] >=0:
#             transform = True
            transform = False
            if transform :
                mat = np.dot(TTrue[vw.id[i][j]],BB[vw.id[i][j]])
            else:
                mat = np.dot(TFalse[vw.id[i][j]],BB[vw.id[i][j]])
            G = np.linalg.inv(scene.rootnode.transformation)
            mat = np.dot(G,mat)
            newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))
end = time.time()

print("TIME : ", end-start)

p = mp.plot(newv, f,v[:, 0],shading={"scale": 2.5,"side": "BackSide","wireframe":True},return_plot=True)  
# p = mp.plot(newv, f,v[:, 0],shading={"scale": 2.5,"wireframe":True},return_plot=True)  

# draw_original_wireframe()
# draw_bones()
draw_vertices_affected_by_boneID(0)


# p.save("skinning.html")


TIME :  0.06154012680053711


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(222.81199…

red points are the ones affected by : astroBoy_newSkeleton_spine02


In [ ]:
b0 = B(0)
b1 = B(1)
b2 = B(2)
print(b0)
print(b1)
print(b2)
b01 = np.dot(b0,b1)
b012 = np.dot(b01,b2)
print(b01)
print(b012)
ib0 = np.linalg.inv(B(0))
print(ib0)

[[ 0.          0.19124199  0.981543   -1.47623003]
 [ 0.          0.981543   -0.19124199 -9.44237041]
 [-1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[  0.          -0.139543     0.99021602   2.42648005]
 [  0.           0.99021602   0.139543   -11.55200005]
 [ -1.           0.           0.           0.        ]
 [  0.           0.           0.           1.        ]]
[[  0.          -0.139543     0.99021602   2.42648005]
 [  0.           0.99021602   0.139543   -12.3039999 ]
 [ -1.           0.           0.           0.        ]
 [  0.           0.           0.           1.        ]]
[[ -0.981543     0.18937089   0.02668648  -3.68545755]
 [  0.19124199   0.9719396    0.13696745 -20.78115525]
 [  0.           0.139543    -0.99021602  -2.42648005]
 [  0.           0.           0.           1.        ]]
[[-2.66864810e-02  3.24485537e-01 -9.45514223e-01 -8.39717144e+00]
 [-1.36967452e-01  9.35743682e-01  3.24998251e-01 -3.22758552e+01

# CGA Method -> Models Working: ManosModeld, ManosModel2



In [ ]:
from clifford.g3c import *
from clifford.tools.g3c import *
from clifford import Cl, conformalize
from dual_quaternion import *
from quaternion import *

G3, blades_g3 = Cl(3)
G3c, blades_g3c, stuff = conformalize(G3)




def to_angle_axis_translation(dq):
    """ 
    Deconstructs a (unit) dual quaternion that corresponds to first to a rotation 
    around an axis by a given angle and then a translation towards the trans vector. 
    The function returns the angle, the (unit) axis, and the translation vector.
    """
    mydq = dq.copy()
#     mydq.normalize()
    if ( not mydq.is_normalized):
        print('The dual quaternion is not unit and therefore it does not correspond to a rigid movement')
    else:
        t = mydq.to_pose()[0:3]
        r = mydq.to_pose()[3:7]
        qr = Quaternion(r[0],r[1],r[2],r[3])
        axis = qr.angle_axis()[0:3]
        angle= qr.angle_axis()[3]
        return angle, axis, t

def matrix_to_motor(M):
    "The matrix has to represent rotation only, no scaling of x,y or z."
    phi,axis,trans = to_angle_axis_translation(DualQuaternion.from_transformation_matrix(M))
    # axis from euc to cga and normalization
    axis = axis[0]*e1+axis[1]*e2+axis[2]*e3
    axis = axis/norm(axis)
    # update trans from euclidean vector to  cga
    t = trans[0]*e1+trans[1]*e2+trans[2]*e3 

    I3 = e1*e2*e3 
        
    R = e**(-(axis*I3)*(phi/2))   # rotor
    T = e**(-1/2*t*einf)          # translator
    return T*R

def up_cga_point_to_euc_point(mv):
    down = fast_down(mv)
    return np.array([down[e1], down[e2], down[e3]])



In [ ]:
# scene = load('../models/ManosModel2.dae')
scene = load('astroBoy_walk.dae.dae','dae')
# scene = load('../models/astroBoy_walk2.dae')

mesh = scene.meshes[0] 
v = mesh.vertices
f = mesh.faces
b = mesh.bones

vw = vertex_weight()
for boneID in range(len(b)):
    for i in range(len(b[boneID].weights)):
        vw.add(b[boneID].weights[i].vertexid, boneID ,b[boneID].weights[i].weight)
        
# =================================================
# EVALUATING TRANSFORMATION MATRICES IN ELEGANT WAY
# =================================================
# original way was :
# t0 = scene.rootnode.children[0].children[0].transformation
# t1 = scene.rootnode.children[0].children[0].children[0].transformation
# t2 = scene.rootnode.children[0].children[0].children[0].children[0].transformation

bone_names = [str(b[i]) for i in range(len(b))]
t = np.zeros([len(b),4,4])
read_tree(scene.rootnode)


# =================================================
# APPLYING EXTRA TRANSFORMATIONS IN JOINTS
# =================================================
M = np.zeros([len(b),4,4])
for i in range(len(b)):
    M[i] = np.identity(4)

# M[0][0:3,0:3] = eulerAnglesToRotationMatrix([0.5,0,0]) 
# M[0][0:3,3] = [1,1,0]
# M[0] = np.dot(M[0],np.diag([1,1,1,1]))

M[1][0:3,0:3] = eulerAnglesToRotationMatrix([0.7,0.3,0.4])
M[1][0:3,3] = [0,0,0]
# M[1] = np.dot(np.diag([1,1.3,1,1]),M[1])

# M[2][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.7])
# M[2][0:3,3] = [0,0,0]
# M[2] = np.dot(M[2],np.diag([1,1/2,1,1]))


# =================================================

cgav = [up(vertex[0]*e1+vertex[1]*e2+vertex[2]*e3) for vertex in v]

newv = np.zeros([(len(v)),3])

TTTRUE = [matrix_to_motor(T(i,True)) for i in range(len(b))]
TTFALSE = [matrix_to_motor(T(i,False)) for i in range(len(b))]
BBB = [matrix_to_motor(B(i)) for i in range(len(b))]


start = time.time()
for i in range(len(v)):
    for j in range(4):
        if vw.id[i][j] >=0:
            transform = True
#             transform = False
            if transform:
#                 mat = np.dot(TTrue[vw.id[i][j]],BB[vw.id[i][j]])
                rotor = TTTRUE[vw.id[i][j]]*BBB[vw.id[i][j]]
            else:
#                 mat = np.dot(TFalse[vw.id[i][j]],BB[vw.id[i][j]])
                rotor = TTFALSE[vw.id[i][j]]*BBB[vw.id[i][j]]
#             newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))
            newv[i] = newv[i] + vw.weight[i][j]*up_cga_point_to_euc_point(rotor*cgav[i]*~rotor) # WORKS
end = time.time()
print("TIME : ", end-start)


p = mp.plot(newv, f,v[:, 0],shading={"scale": 2.5,"side": "BackSide","wireframe":True},return_plot=True)  

draw_original_wireframe()
# draw_bones()
# draw_vertices_affected_by_boneID(0)


# p.save("skinning.html")

# print(newv[0:30])


TIME :  0.9064309597015381


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.3120335…

The problem in the code above is that we down project a lot of times and therefore the run time is **LOWER** when compared to the code below where we down project only once, at the end of the evaluation. 

The reason is that adding multivectors demands adding 32 (actually 12) coefficients whereas, the addition of down projecting first reduces the coefficients to 3, and therefore less operations/running time!

In [ ]:
#### INEFFICIENT METHOD ####

## scene = load('../models/ManosModel2.dae')
scene = load('astroBoy_walk.dae.dae','dae')
# scene = load('../models/astroBoy_walk2.dae')

mesh = scene.meshes[0] 
v = mesh.vertices
f = mesh.faces
b = mesh.bones

vw = vertex_weight()
for boneID in range(len(b)):
    for i in range(len(b[boneID].weights)):
        vw.add(b[boneID].weights[i].vertexid, boneID ,b[boneID].weights[i].weight)
        
# =================================================
# EVALUATING TRANSFORMATION MATRICES IN ELEGANT WAY
# =================================================
# original way was :
# t0 = scene.rootnode.children[0].children[0].transformation
# t1 = scene.rootnode.children[0].children[0].children[0].transformation
# t2 = scene.rootnode.children[0].children[0].children[0].children[0].transformation

bone_names = [str(b[i]) for i in range(len(b))]
t = np.zeros([len(b),4,4])
read_tree(scene.rootnode)


# =================================================
# APPLYING EXTRA TRANSFORMATIONS IN JOINTS
# =================================================
M = np.zeros([len(b),4,4])
for i in range(len(b)):
    M[i] = np.identity(4)

# M[0][0:3,0:3] = eulerAnglesToRotationMatrix([0.5,0,0]) 
# M[0][0:3,3] = [1,1,0]
# M[0] = np.dot(M[0],np.diag([1,1,1,1]))

M[1][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.4])
M[1][0:3,3] = [0,0,0]
# M[1] = np.dot(np.diag([1,1.3,1,1]),M[1])

# M[2][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.7])
# M[2][0:3,3] = [0,0,0]
# M[2] = np.dot(M[2],np.diag([1,1/2,1,1]))


# =================================================

cgav = [up(vertex[0]*e1+vertex[1]*e2+vertex[2]*e3) for vertex in v]
newv = [0 for i in range(len(v))]
# newv = np.array([(len(v)),3],0)


TTTRUE = [matrix_to_motor(T(i,True)) for i in range(len(b))]
TTFALSE = [matrix_to_motor(T(i,False)) for i in range(len(b))]
BBB = [matrix_to_motor(B(i)) for i in range(len(b))]


start = time.time()
for i in range(len(v)):
    for j in range(4):
        if vw.id[i][j] >=0:
            transform = True
#             transform = False
            if transform:
#                 mat = np.dot(TTrue[vw.id[i][j]],BB[vw.id[i][j]])
                rotor = TTTRUE[vw.id[i][j]]*BBB[vw.id[i][j]]
            else:
#                 mat = np.dot(TFalse[vw.id[i][j]],BB[vw.id[i][j]])
                rotor = TTFALSE[vw.id[i][j]]*BBB[vw.id[i][j]]
#             newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))
            newv[i] = newv[i] + vw.weight[i][j]*(rotor*cgav[i]*~rotor) # WORKS

def up_cga_point_to_euc_point_list(mv):
    down = fast_down(mv)
    return [down[e1], down[e2], down[e3]]
    
eucnewv = [up_cga_point_to_euc_point_list(vertex) for vertex in newv]
end = time.time()
print("TIME : ", end-start)


p = mp.plot(np.array(eucnewv), f,v[:, 0],shading={"scale": 2.5,"side": "BackSide","wireframe":True},return_plot=True)  
# p = mp.plot(eucnewv, return_plot=True)
draw_original_wireframe()
# draw_bones()
# draw_vertices_affected_by_boneID(0)


# p.save("skinning.html")

# print(newv[0:30])



TIME :  0.07455611228942871


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.019150…

# TEST AREA BELOW

In [ ]:
def dq_to_bivector(dq):
    """ 
    Returns the bivector form of a dual quaternion dq
    
    Remarks: 
    i = e1^e2 = e12
    j = e3^e1 = -e13
    k = e2^e3 = e23
    i*epsilon = einf^e3 = -e34-e35 
    j*epsilon = einf^e2 = -e24-e25 
    k*epsilon = einf^e1 = -e14-e15
    epsilon = e1^e2^e3^einf = e1234+e1235
    """
    return dq.r_x*e12 - dq.r_y*e13 + dq.r_z*e23 + dq.r_w \
           + dq.t_x*(-e34-e35) + dq.t_y*(-e24-e25) + dq.t_z*(-e14-e15) + dq.t_w*(e1234+e1235)

def transformation_matrix_to_cga(matrix):
    return dq_to_bivector( DualQuaternion.from_transformation_matrix(matrix) )


def bivector_to_dq(bv):
    """ 
    Returns the dual quaternion dq that corresponds to the bivector bv
    
    Remarks: 
    i = e1^e2 = e12
    j = e3^e1 = -e13
    k = e2^e3 = e23
    i*epsilon = einf^e3 = -e34-e35 
    j*epsilon = einf^e2 = -e24-e25 
    k*epsilon = einf^e1 = -e14-e15
    epsilon = e1^e2^e3^einf = e1234+e1235
    
    Since bv is assumed to be a dq, all other blades coefficients are supposed to equal 0
    and the coefficients of e1234 must equal the one of e1235 and 
    """
    assert( bv[e1234] == bv[e1235] )  # due to epsilon 
    assert( bv[e14] == bv[e15] ) # due to k*epsilon 
    assert( bv[e24] == bv[e25] ) # due to j*epsilon 
    assert( bv[e34] == bv[e35] ) # due to i*epsilon 
    assert( bv.odd.clean() == 0) # round odd part --> it should be 0, i.e., no odd vectors in bv


    return  DualQuaternion.from_vector([bv[e12],-bv[e13],bv[e23],bv[0],-bv[e34],-bv[e24],-bv[e14],bv[e1234]])

def cga_to_transformation_matrix(bivector):
    dq = bivector_to_dq(bivector)
    return dq.to_matrix()

In [ ]:
def TransMatrixToCGA(matrix):
    m = np.copy(matrix)
    translate = [m[0,3],m[1,3],m[2,3]]
    mt = m.transpose()
    sx = np.sqrt(np.dot(m[:,0],m[:,0]))
    sy = np.sqrt(np.dot(m[:,1],m[:,1]))
    sz = np.sqrt(np.dot(m[:,2],m[:,2]))
    if sx and sy and sz:
        m[0:3,0:3] = np.dot(m[0:3,0:3],np.diag([1/sx,1/sy,1/sz]))
    return transformation_matrix_to_cga(m) #,sx,sy,sz,m


M = np.identity(4)

M[0:3,0:3] = eulerAnglesToRotationMatrix([0.5,0.5,0.7]) 
M[0:3,3] = [1,1,0]
# M = np.dot(M,np.diag([5,4,3,1]))



CGA_M = transformation_matrix_to_cga(M)
CGA_M = TransMatrixToCGA(M)
print("M=\n", M)
print("CGA_M=\n", CGA_M)
# M = cga_to_transformation_matrix(CGA_M)

T = transformation_matrix_to_cga(M)


v = np.array([2,3,5])


############# applying Transformation via Matrix
v2 = vertex_apply_M(v,M)
print("v2:",v2)
print("#############")

########### apply transformation Via Dual Quaternion
qp = Quaternion(v[0], v[1], v[2], 0) 
qI = Quaternion(0, 0, 0, 1) 
dqv = DualQuaternion(qI,qp) 
dq = DualQuaternion.from_transformation_matrix(M)
dq_prime = dq.conjugate_translation()
dqv2 = dq*dqv*dq_prime # we apply the transformation pattern
print('initial point: ',dqv.q_dual)
print('rotated point: ',dqv2.q_dual) 
print("#############")
########### apply transformation Via CGA

# print(up(v[0]*e1+v[1]*e2+v[2]*e3))

# cgav = dq_to_bivector(dqv)
# print(cgav)
# T = transformation_matrix_to_cga(M)
# print(T*cgav*~(T))
# print(dq_to_bivector(T_dq))
# print(dq_to_bivector(T_dq)*dq_to_bivector(point_dq)*(~dq_to_bivector(T_dq)))
# print(dq_to_bivector(T_dq)*dq_to_bivector(point_dq)*dq_to_bivector(T_dq_prime))
# print(dq_to_bivector(translated_point_dq))


# dq = DualQuaternion.from_transformation_matrix(matrix)

phi,axis,trans = to_angle_axis_translation(dq)

print(to_angle_axis_translation(dq))
# update axis from euclidean vector to normalized cga
axis = axis[0]*e1+axis[1]*e2+axis[2]*e3
axis = axis/norm(axis)
print(axis)
I3 = e1*e2*e3 # I3, note that *=geometric product

R = e**(-(axis*I3)*(phi/2)) # rotor

print("Rotor = ",R)
# update trans from euclidean vector to  cga
t = trans[0]*e1+trans[1]*e2+trans[2]*e3 
T = e**(-1/2*t*einf) # translator
print('Translator = ',T)

Motor = T*R
print("Motor = ",Motor)
print("T = ",T)

# cgav = up(v[0]*e1+v[1]*e2+v[2]*e3)
v = np.array([2,3,5])
cgav = up(v[0]*e1+v[1]*e2+v[2]*e3)
# print(down(Motor*cgav*~Motor))
print(down(apply_rotor(cgav,Motor))) # faster way to apply rotor instead of writing it
print("#############")


def matrix_to_motor(M):
    "The matrix has to represent rotation only, no scaling of x,y or z."
    phi,axis,trans = to_angle_axis_translation(DualQuaternion.from_transformation_matrix(M))
    # axis from euc to cga and normalization
    axis = axis[0]*e1+axis[1]*e2+axis[2]*e3
    axis = axis/norm(axis)
    # update trans from euclidean vector to  cga
    t = trans[0]*e1+trans[1]*e2+trans[2]*e3 

    I3 = e1*e2*e3 
        
    R = e**(-(axis*I3)*(phi/2))   # rotor
    T = e**(-1/2*t*einf)          # translator
    return T*R

# print(matrix_to_motor(M))

### We can obtain T,R from M if we want
# R = Motor(e123)
# T = (Motor*~R).normal()



M=
 [[ 0.67121217 -0.38955611  0.63065067  1.        ]
 [ 0.56535421  0.81928486 -0.09563963  1.        ]
 [-0.47942554  0.42073549  0.77015115  0.        ]
 [ 0.          0.          0.          1.        ]]
CGA_M=
 0.90286 + (0.14298^e12) - (0.30738^e13) - (0.0822^e14) - (0.0822^e15) + (0.26441^e23) - (0.31923^e24) - (0.31923^e25) - (0.58364^e34) - (0.58364^e35) - (0.22518^e1234) - (0.22518^e1235)
v2: [4.32700932 4.11036483 4.15411116]
#############
initial point:  [2. 3. 5. 0.]
rotated point:  [ 4.32700932e+00  4.11036483e+00  4.15411116e+00 -2.22044605e-16]
#############
(0.8888257241934697, array([0.3325736 , 0.71494931, 0.61501406]), array([ 1.00000000e+00,  1.00000000e+00, -5.55111512e-17]))
(0.33257^e1) + (0.71495^e2) + (0.61501^e3)
Rotor =  0.90286 - (0.26441^e12) + (0.30738^e13) - (0.14298^e23)
Translator =  1.0 - (0.5^e14) - (0.5^e15) - (0.5^e24) - (0.5^e25)
Motor =  0.90286 - (0.26441^e12) + (0.30738^e13) - (0.58364^e14) - (0.58364^e15) - (0.14298^e23) - (0.31923^e24) - (0.

In [ ]:
print(v[1])
print(cgav[1])
print(vw.id[1])
# print(TTT[0])
# print(TTT[1])
# print(TTT[2])
# print(TTT[0]*BBB[0])
m = TTTRUE[0]*BBB[0]

nn = [0 for i in range(5)]
print(nn)
print(nn[0]+m*cgav[1]*~m)




3
2.0
[ 0  1  2 -1]
[0, 0, 0, 0, 0]
2.0


In [ ]:
# rotor = matrix_to_motor(T(vw.id[i][j],transform))*matrix_to_motor(B(vw.id[i][j]))
# print(matrix_to_motor(B(2)))
# print(matrix_to_motor(T(2)))


In [ ]:
v = np.array([2,3,5])
fast_up(v[0]*e1+v[1]*e2+v[2]*e3)
fast_down(fast_up(v[0]*e1+v[1]*e2+v[2]*e3))
up_cga_point_to_euc_point(fast_up(v[0]*e1+v[1]*e2+v[2]*e3))

array([2., 3., 5.])

In [ ]:
scene = load('astroBoy_walk2.dae')
mesh = scene.meshes[0] 
v0 = mesh.vertices
f0 = mesh.faces
# p = mp.plot(v0, f0,v0[:, 0],shading={"scale": 2.5,"wireframe":True},return_plot=True) 

mesh = scene.meshes[3] 
v3 = mesh.vertices
f3 = mesh.faces

L = len(v0)
print(L)
print(f3[0:10])


f3 = [ face+[L,L,L] for face in f3 ]
print(f3[0:10])
v0=np.concatenate((v0,v3))
f0=np.concatenate((f0,f3))
p = mp.plot(v0, f0,v0[:, 0],shading={"scale": 2.5,"wireframe":True},return_plot=True) 

2006
[[ 0  1  2]
 [ 0  2  3]
 [ 4  5  6]
 [ 4  6  7]
 [ 8  9 10]
 [ 8 10 11]
 [12 13 14]
 [12 14 15]
 [16 17 18]
 [16 18 19]]
[array([2006, 2007, 2008]), array([2006, 2008, 2009]), array([2010, 2011, 2012]), array([2010, 2012, 2013]), array([2014, 2015, 2016]), array([2014, 2016, 2017]), array([2018, 2019, 2020]), array([2018, 2020, 2021]), array([2022, 2023, 2024]), array([2022, 2024, 2025])]


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 10.0…

In [ ]:
scene = load('astroBoy_walk.dae','dae')


# m_GlobalInverseTransform = m_pScene->mRootNode->mTransformation;
# m_GlobalInverseTransform.Inverse();
m_GlobalInverseTransform = np.linalg.inv(scene.rootnode.transformation)
print(m_GlobalInverseTransform)

# print(scene.rootnode.name)
# print(scene.rootnode.transformation)
# print(scene.rootnode.children[0].name)
# print(scene.rootnode.children[0].transformation)
# print(scene.rootnode.children[1].name)
# print(scene.rootnode.children[1].transformation)

# print(scene.rootnode.children[0].children[0].name)
# print(scene.rootnode.children[0].children[0].transformation)

# MM = np.zeros([len(b),4,4])


MM = np.zeros([len(b),4,4])
def read_tree_names(node,parentmatrix):
    p = np.dot(parentmatrix,node.transformation)
    if node.name in bone_names:
        index = bone_names.index(node.name)
        t[index] = node.transformation
        MM[index] = p
    for child in node.children:
        read_tree_names(child,p)
        
read_tree_names(scene.rootnode,np.identity(4))

print(MM)
print(TFalse)
# print(MM[1])
# print(MM[2])



[[100.00000224   0.           0.           0.        ]
 [  0.         100.00000224   0.           0.        ]
 [  0.           0.         100.00000224   0.        ]
 [  0.           0.           0.           1.        ]]


ValueError: setting an array element with a sequence.

In [ ]:
# scene = load('../models/ManosModel2.dae')
# scene = load('../models/ManosModeld.dae','dae')
scene = load('astroBoy_walk2.dae')

mesh = scene.meshes[3] 
v = mesh.vertices
f = mesh.faces
b = mesh.bones

vw = vertex_weight()
for boneID in range(len(b)):
    for i in range(len(b[boneID].weights)):
        vw.add(b[boneID].weights[i].vertexid, boneID ,b[boneID].weights[i].weight)
        

bone_names = [str(b[i]) for i in range(len(b))]
t = np.zeros([len(b),4,4])
read_tree(scene.rootnode)



MM = np.zeros([len(b),4,4])
def read_tree_names(node,parentmatrix):
    p = np.dot(parentmatrix,node.transformation)
    if node.name in bone_names:
        index = bone_names.index(node.name)
        t[index] = node.transformation
        MM[index] = p
    for child in node.children:
        read_tree_names(child,p)
        
read_tree_names(scene.rootnode,np.identity(4))



# =================================================
# APPLYING EXTRA TRANSFORMATIONS IN JOINTS
# =================================================
M = np.zeros([len(b),4,4])
for i in range(len(b)):
    M[i] = np.identity(4)

# M[0][0:3,0:3] = eulerAnglesToRotationMatrix([0.5,0,0]) 
# M[0][0:3,3] = [1,1,0]
# M[0] = np.dot(M[0],np.diag([1,1,1,1]))

M[1][0:3,0:3] = eulerAnglesToRotationMatrix([0.7,0.3,0.4])
M[1][0:3,3] = [0,0,0]
M[1] = np.dot(np.diag([1,1.3,1,1]),M[1])

# M[2][0:3,0:3] = eulerAnglesToRotationMatrix([0,0,0.7])
# M[2][0:3,3] = [0,0,0]
# M[2] = np.dot(M[2],np.diag([1,1/2,1,1]))


# =================================================
        
newv = np.zeros([(len(v)),3])

TTrue = [T(i,True) for i in range(len(b))]
TFalse = [T(i,False) for i in range(len(b))]
BB = [B(i) for i in range(len(b))]

import time

start = time.time()
for i in range(len(v)):
    for j in range(4):
        if vw.id[i][j] >=0:
#             transform = True
            transform = False
            if transform :
                mat = np.dot(TTrue[vw.id[i][j]],BB[vw.id[i][j]])
            else:
#                 mat = np.dot(TFalse[vw.id[i][j]],BB[vw.id[i][j]])
                mat = np.dot(MM[vw.id[i][j]],BB[vw.id[i][j]])
            G = np.linalg.inv(scene.rootnode.transformation)
            mat = np.dot(G,mat)
            newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))
end = time.time()

print("TIME : ", end-start)

# p = mp.plot(newv, f,v[:, 0],shading={"scale": 2.5,"side": "BackSide","wireframe":True},return_plot=True)  
# p = mp.plot(newv, f,newv[:, 0],shading={"wireframe":True})  


p = mp.subplot(newv, f,newv[:, 0], shading={"wireframe":True},s=[1,2,0])


newv = np.zeros([(len(v)),3])

start = time.time()
for i in range(len(v)):
    for j in range(4):
        if vw.id[i][j] >=0:
#             transform = True
            transform = False
            if transform :
                mat = np.dot(TTrue[vw.id[i][j]],BB[vw.id[i][j]])
            else:
                mat = np.dot(TFalse[vw.id[i][j]],BB[vw.id[i][j]])
#                 mat = np.dot(MM[vw.id[i][j]],BB[vw.id[i][j]])
            G = np.linalg.inv(scene.rootnode.transformation)
            mat = np.dot(G,mat)
            newv[i] = newv[i] + vw.weight[i][j]*(vertex_apply_M(v[i],mat))
end = time.time()

print("TIME : ", end-start)

# p = mp.plot(newv, f,v[:, 0],shading={"scale": 2.5,"side": "BackSide","wireframe":True},return_plot=True)  


mp.subplot(newv, f,newv[:, 0],shading={"wireframe":True},s=[1,2,1], data=p)


# draw_original_wireframe()
# draw_bones()
# draw_vertices_affected_by_boneID(0)


# p.save("skinning.html")

ValueError: grade must be an integer

In [ ]:
# see https://salsa.debian.org/debian/assimp/blob/d14d34856c2fd024b15781cf48ffcb7b2ce0146f/port/PyAssimp/pyassimp/structs.py
# check : class NodeAnim(Structure)

print(scene.animations[0].channels[0].nodename.data)
print(scene.animations[0].channels[0].positionkeys[0].time)
print(scene.animations[0].channels[0].positionkeys[0].value)
print(scene.animations[0].channels[0].rotationkeys[0].time)
print(scene.animations[0].channels[0].rotationkeys[0].value) # a quaternion (w,x,y,z)
print(scene.animations[0].channels[0].scalingkeys[0].time)
print(scene.animations[0].channels[0].scalingkeys[0].value)



b'astroBoy_newSkeleton_root'
0.041666001081466675
[ 0.          6.84325981 -0.145007  ]
0.041666001081466675
[0.73393226 0.03406313 0.67763859 0.03145043]
0.041666001081466675
[0.99999988 0.99999994 1.        ]


In [ ]:
# # is it possible to obtain T,R,D from T*R*D ???

# Motor = MMM2[3]
# R_mod = Motor(e123)
# T_mod = (Motor*~R_mod)

# scale_factor = 2.5
# D = 1 + ((1-scale_factor)/(1+scale_factor))*(einf^eo)

# print("T = ",T_mod)
# print("R = ",R_mod.normal())
# print("D = ",D)
# print("T*R = ", Motor)
# print("T*R*D = ",(Motor*D))

# print("="*8)
# b = (Motor*D)

# # you know R
# print(b(e123).normal())
# print(b(e45).normal())

# print(e45*e45)

# print(Motor[0])
# print(Motor[e45])
# print(b[0])
# print(b[e45])

# x = Motor[0]
# y = Motor[e45]
# z = b[0]

# # if you know both T*R and T*R*D yes
# print((z-x)/y)
# print(D[e45])

In [ ]:
# counting operations - test files

# R = axis_angle_to_rotor([2,2,2],-0.7)
# T = vector_to_translator([1,5,1])
# D = scale_to_dilator(2)

# C = up_vertex([1,2,3])
# print(T)
# print(R)
# print(D)
# print(C)
# print("="*10)
# print(e14*e12)
# print(e15*e12)
# print(e24*e12)
# print(e34*e12)
# print(e35*e12)
# print(e14*e12*e45)
# print(e15*e12*e45)
# print(e24*e12*e45)
# print(e34*e12*e45)
# print(e35*e12*e45)
# print(e14*e12*e45*e1)
# print(e15*e12*e45*e1)
# print(e24*e12*e45*e1)
# print(e34*e12*e45*e1)
# print(e35*e12*e45*e1)
# print(e14*e12*e45*e4)
# print(e15*e12*e45*e4)
# print(e24*e12*e45*e4)
# print(e34*e12*e45*e4)
# print(e35*e12*e45*e4)
# print(e14*e12*e45*e5)
# print(e15*e12*e45*e5)
# print(e24*e12*e45*e5)
# print(e34*e12*e45*e5)
# print(e35*e12*e45*e5)

# M = T*R*D
# print(M)
# M2 = ~M
# print(M2)
# M3 = (~D)*(~R)*(~T)
# print(M2-M3)


# print("="*10)
# print(C)
# print(D)
# print(~D)
# print(D*C*~D)

# print("="*10)
# print(down(C))
# print(down(R*C*~R))
# print(R*down(C)*~R)
# print("="*10)
# print(down(C))
# print(down(T*C*~T))
# print(T*down(C)*~T)


# print(D*C)

# print(T)
# print(~T)
# print(C)
# # print(e45*e5)
# # print(eo*einf)
# # print(eo*einf*eo)
# # print((eo*einf*e3)*(eo*einf))
# print(T*C)